### ISSUE TITLE
Include generated theme JSON in repo?

### ISSUE THREAD

**Issue by brianleewow** [victor-gp/lucario-vscode-theme#1]
I'd love to use this theme at work, but the custom locked down vs code implementation I use doesn't let theme extensions run scripts. Would it be possible to include the generated JSON in the repo? Thanks!

**Comment by victor-gp** [comment]
Hi @brianleewow, appreciate the interest! :purple_heart: 

Would it work if I added the JSON file as an asset to [each release](https://github.com/victor-gp/lucario-vscode-theme/releases) going forward?

**Comment by victor-gp** [comment]
That said, I'm not sure I understand the problem. 

If I'm not mistaken, the installed extension shouldn't run scripts. We run them all at build time, to transform the YAML file to JSON. Then we only package that JSON file and some extras (`README.md`, preview screenshot) for the extension.

Can you install & use any other theme extension? May it be a problem with those extra files, rather than the scripts? Is it that your editor's "firewall" looks into the GitHub repo and detects those scripts?

In any case, I did plan to expose the generated JSON, ideally in Releases. Or any other place if that's not convenient.

Let me know if you do need this and I'll try to get to it asap.

**Comment by brianleewow** [comment]
Yes, adding the JSON to the assets would work!

The situation is kind of hard to explain, but yes our system pulls extensions from github based on an allowlist.

**Comment by victor-gp** [comment]
[There you go.](https://github.com/victor-gp/lucario-vscode-theme/releases/tag/v2.3.1) :smile: 

I'll try to automate this so a release's made for every tag going forward, including that JSON theme file.

**Comment by victor-gp** [comment]
If you find this project helpful, please give it a GitHub star! :star: 

That way, you'll also get a notification every time we make a release. :D

Lastly, don't hesitate to open an issue if you're unhappy about how we syntax highlight any part of a language, or how we colorize the broader editor. Feedback is super welcome!

**Comment by victor-gp** [comment]
I've fully automated this.

From v2.3.3, both publishing to the VS Marketplace and making a release on GitHub are automated. The GitHub release includes the JSON version of the theme as an asset.

The automation is triggered by pushing a version tag to GitHub.
